[package]
name = "lox"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { version = "1.0.86", features = ["backtrace"] }
clap = { version = "4.5.16", features = ["derive"] }
colored = "2.1.0"
pretty_assertions = "1.4.1"
strum = "0.26.3"
strum_macros = "0.26.4"
textwrap = "0.16.1"
